description: This playbook gets all available assets ( alerts, vulnerabilities and
  devices) and send then to configured PANW third-party integration SIEM server.
id: Bulk Export to SIEM - PANW IoT 3rd Party Integration
inputs: []
name: Bulk Export to SIEM - PANW IoT 3rd Party Integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8e9250c5-18aa-4c28-88d5-cbb378d65162
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 8e9250c5-18aa-4c28-88d5-cbb378d65162
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 650,
          "y": -80
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
      - "4"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Syslog Sender
      using:
        simple: PANW IoT 3rd Party SIEM Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: e9fb706d-fe34-4650-834e-aa51c84f7bc6
      iscommand: false
      name: Is Syslog Sender(SIEM) Enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: e9fb706d-fe34-4650-834e-aa51c84f7bc6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 660,
          "y": 90
        }
      }
  "2":
    continueonerror: true
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      integration_name:
        simple: siem
      integrationName:
        simple: siem
      message:
        simple: Syslog Sender (SIEM) instance is not enabled
      playbook_name:
        simple: Bulk Export to SIEM - PANW IoT 3rd Party Integration
      playbookName:
        simple: Bulk Export to SIEM - PANW IoT 3rd Party Integration
      status:
        simple: disabled
      type:
        simple: device
      using:
        simple: PANW IoT 3rd Party Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a status message back to PANW IOT cloud.
      id: df039480-798c-4bb9-83bc-c525a2737ed4
      iscommand: true
      name: Send disabled status to PANW IoT cloud
      script: '|||panw-iot-3rd-party-report-status-to-panw'
      type: regular
      version: -1
    taskid: df039480-798c-4bb9-83bc-c525a2737ed4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": 270
        }
      }
  "3":
    continueonerror: true
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: device
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      syslog_sender_instance:
        simple: PANW IoT 3rd Party SIEM Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation retrieves all specified assets from the PANW IoT
        cloud and sends them to the SIEM server.
      id: 5a9fde2f-1a69-429b-88ea-35c2f3bde5e6
      iscommand: false
      name: Send all PANW IoT devices to SIEM
      script: f8b9de95-9ac9-4e6d-89d7-b3bf92e9e14c
      type: regular
      version: -1
    taskid: 5a9fde2f-1a69-429b-88ea-35c2f3bde5e6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 260,
          "y": 500
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: alert
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      syslog_sender_instance:
        simple: PANW IoT 3rd Party SIEM Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation retrieves all specified assets from the PANW IoT
        cloud and sends them to the SIEM server.
      id: f357b43a-b665-49d8-83bd-c7f2870857af
      iscommand: false
      name: Send all PANW IoT alerts to SIEM
      script: f8b9de95-9ac9-4e6d-89d7-b3bf92e9e14c
      type: regular
      version: -1
    taskid: f357b43a-b665-49d8-83bd-c7f2870857af
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 500
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      asset_type:
        simple: vulnerability
      panw_iot_3rd_party_instance:
        simple: PANW IoT 3rd Party Integration Instance
      syslog_sender_instance:
        simple: PANW IoT 3rd Party SIEM Integration Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation retrieves all specified assets from the PANW IoT
        cloud and sends them to the SIEM server.
      id: b012d21a-0e41-421b-8046-9e53c7fa7a25
      iscommand: false
      name: Send all PANW IoT vulnerabilities to SIEM
      script: f8b9de95-9ac9-4e6d-89d7-b3bf92e9e14c
      type: regular
      version: -1
    taskid: b012d21a-0e41-421b-8046-9e53c7fa7a25
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1060,
          "y": 500
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 810a508f-b736-4657-84fb-f1d04149fca3
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 810a508f-b736-4657-84fb-f1d04149fca3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 850
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1025,
        "width": 1210,
        "x": 230,
        "y": -80
      }
    }
  }
fromversion: 6.0.0
tests:
- No tests (auto formatted)
