description: Export alert and vulnerability to service now
id: export_alert_vul_to_servicenow
inputs: []
name: export_alert_vul_to_servicenow
outputs:
- contextPath: incident
  description: The incident value
  type: unknown
quiet: true
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d8bef144-88b3-4676-8194-4b1284d0053a
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: d8bef144-88b3-4676-8194-4b1284d0053a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 506d0d2f-22d0-4622-80ae-6a7ef915f5d0
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 506d0d2f-22d0-4622-80ae-6a7ef915f5d0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      custom_fields: {}
      fields:
        complex:
          root: incident
          transformers:
          - args:
              field:
                value:
                  simple: alert
            operator: getField
      table_name:
        simple: u_zingbox_alerts_vulnerablilty_incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow v2
      description: Creates a new record in the specified ServiceNow table.
      id: cf7064f3-317a-4c09-81e8-472ef1821fe9
      iscommand: true
      name: servicenow-create-record
      script: ServiceNow v2|||servicenow-create-record
      type: regular
      version: -1
    taskid: cf7064f3-317a-4c09-81e8-472ef1821fe9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 280
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 625,
        "width": 380,
        "x": 450,
        "y": 60
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
