description: This playbook gets all available device inventory from PANW IoT cloud
  send to ServiceNow
id: 7150d634-f40d-474b-8419-e4bab11210af
inputs: []
name: panw_iot_servicenow_device_bulk_sync_playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7a11e867-f09e-46fd-899f-19044b9fe1cf
      iscommand: false
      name: ""
      version: -1
    taskid: 7a11e867-f09e-46fd-899f-19044b9fe1cf
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This script gets all available devices from the IoT cloud and updates/creates
        new endpoint with custom attributes on ServiceNow
      id: aadc009a-4fab-4dca-8f3f-5ae3b26bc286
      iscommand: false
      name: send_bulk_panw_iot_devices_to_servicenow
      script: 189eabd5-8705-467a-8c5a-9499af595521
      type: regular
      version: -1
    taskid: aadc009a-4fab-4dca-8f3f-5ae3b26bc286
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4a131eb7-9279-42fe-8b96-9b2e84bbf726
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4a131eb7-9279-42fe-8b96-9b2e84bbf726
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 4c618995-9c5a-4ac3-83f0-2adb485177d5
      iscommand: false
      name: Is servicenow available
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 4c618995-9c5a-4ac3-83f0-2adb485177d5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: servicenow
      message:
        simple: Servicenow integration is not enabled yet
      playbook-name:
        simple: panw_iot_servicenow_device_bulk_sync_playbook
      status:
        simple: disabled
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: f9d74780-fbd8-438b-8f22-1ba65c40db03
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: f9d74780-fbd8-438b-8f22-1ba65c40db03
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 320
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 21f52d7e-cbe6-4715-888a-c2e3eabf5377
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 21f52d7e-cbe6-4715-888a-c2e3eabf5377
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 555
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 755,
        "width": 780,
        "x": 450,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
