description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  unquarantine a device in ISE
id: panw_iot_ise_unquarantine_playbook
inputs: []
name: panw_iot_ise_unquarantine_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_ise_unquarantine"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 13691756-ae12-4692-84ed-01fd3c2c76d8
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 13691756-ae12-4692-84ed-01fd3c2c76d8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 6ffc1e65-ef84-4df6-8cef-15a111afe179
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 6ffc1e65-ef84-4df6-8cef-15a111afe179
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: alert
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 307105d5-b1f0-4661-8d86-e3d8c4b4a750
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 307105d5-b1f0-4661-8d86-e3d8c4b4a750
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Integration not Configured
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 9da43bf2-21dc-4338-85b0-2e05bc440f1f
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 9da43bf2-21dc-4338-85b0-2e05bc440f1f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 450
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 495,
        "width": 790,
        "x": 40,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
