description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  single vulnerability to SIEM
id: panw_iot_siem_single_vulnerability_playbook
inputs: []
name: panw_iot_siem_single_vulnerability_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_siem_alert"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eb4a09c8-02bb-44ef-8a2e-06e79192d661
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: eb4a09c8-02bb-44ef-8a2e-06e79192d661
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: a88dbea8-61a0-4318-8493-ddcf39e7476b
      iscommand: false
      name: Is  SIEM enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: a88dbea8-61a0-4318-8493-ddcf39e7476b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: SIEM Integration not enabled
      playbook-name:
        simple: panw_iot_siem_single_vulnerability_playbook
      status:
        simple: error
      type:
        simple: vulnerability
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: a481f947-d333-48fa-8ea7-a6156f71d769
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: a481f947-d333-48fa-8ea7-a6156f71d769
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${incident.zb_ticketid}
      asset_type:
        simple: Vulnerabilities
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: Given a id (alert-id, vulnerability-id or mac-address) returns
        the asset details
      id: cd5f823c-02c9-41a9-8bfd-a48e06edb223
      iscommand: true
      name: get-single-vulnerability-details
      script: Palo Alto IoT Third-Party-Integration Base|||get-single-asset-details
      type: regular
      version: -1
    taskid: cd5f823c-02c9-41a9-8bfd-a48e06edb223
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "6":
    continueonerror: true
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      VulnerabilityList:
        simple: ${PaloAltoIoTIntegrationBase.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: Converts vulnerability detail maps to CEF syslogs
      id: 7607ab45-9da7-405c-8bb4-d2f56dcde8ae
      iscommand: true
      name: convert-vulnerabilities-to-cef
      script: Palo Alto IoT Third-Party-Integration Base|||convert-vulnerabilities-to-cef
      type: regular
      version: -1
    taskid: 7607ab45-9da7-405c-8bb4-d2f56dcde8ae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 910
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      address: {}
      facility: {}
      level: {}
      message:
        simple: ${PaloAltoIoTIntegrationBase.VulnerabilitySyslogs}
      port: {}
      protocol: {}
      using:
        simple: PANW IoT Siem Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Syslog Sender
      description: Sends a message to Syslog.
      id: 185a5eb7-00e6-48f7-81d6-2a05ce98ce51
      iscommand: true
      name: syslog-send
      script: Syslog Sender|||syslog-send
      type: regular
      version: -1
    taskid: 185a5eb7-00e6-48f7-81d6-2a05ce98ce51
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 65d6403b-799e-4b2b-8737-42db65e1bf94
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 65d6403b-799e-4b2b-8737-42db65e1bf94
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: Failed to get Vulnerability (${incident.zb_ticketid}) from IoT cloud.
      playbook-name:
        simple: panw_iot_siem_single_vulnerability_playbook
      status:
        simple: error
      type:
        simple: vulnerability
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 683d1c66-a6f8-473a-8222-414f8cdf7c19
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 683d1c66-a6f8-473a-8222-414f8cdf7c19
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "10":
    continueonerror: true
    id: "10"
    ignoreworker: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PaloAltoIoTIntegrationBase.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 2a250d37-7b95-4a9c-873b-b99daba81375
      iscommand: false
      name: Exists
      script: Exists
      type: condition
      version: -1
    taskid: 2a250d37-7b95-4a9c-873b-b99daba81375
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 685,
          "y": 720
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: No Vulnerability found with given ID - ${incident.zb_ticketid}
      playbook-name:
        simple: panw_iot_siem_single_vulnerability_playbook
      status:
        simple: success
      type:
        simple: vulnerability
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: e6f3c72a-73ff-460f-81bc-da94f1a1990c
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: e6f3c72a-73ff-460f-81bc-da94f1a1990c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 910
        }
      }
  "12":
    continueonerror: true
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: Successfully sent Vulnerability (${incident.zb_ticketid}) to SIEM
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: success
      type:
        simple: vulnerability
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: bbce7c68-6b03-40f8-817c-558e4eb22660
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: bbce7c68-6b03-40f8-817c-558e4eb22660
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1295
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 80da2785-2831-4355-87b4-ae70b459ce32
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 80da2785-2831-4355-87b4-ae70b459ce32
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1475
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1520,
        "width": 1360,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
