description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to un-quarantine
  a device in ISE
id: panw_iot_ise_unquarantine_playbook
inputs: []
name: panw_iot_ise_unquarantine_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_ise_quarantine"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dc828732-979d-4e90-8811-577268f23d68
      iscommand: false
      name: ""
      version: -1
    taskid: dc828732-979d-4e90-8811-577268f23d68
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 260,
          "y": -500
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE Copy
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 38997ab5-91a5-43f3-823d-e1cf0a70b3a7
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 38997ab5-91a5-43f3-823d-e1cf0a70b3a7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 260,
          "y": -380
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Cisco ISE instance is not enabled
      playbook-name:
        simple: panw_iot_ise_unquarantine_playbook
      status:
        simple: disabled
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: a9e977d4-f5ee-4930-85b7-a1906c070417
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: a9e977d4-f5ee-4930-85b7-a1906c070417
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": -130
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      macAddress:
        simple: ${incident.macAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns an endpoint ID, by its MAC address.
      id: c24d2176-d3d3-4c0c-8a83-e63359322dd3
      iscommand: true
      name: cisco-ise-get-endpoint-id
      script: '|||cisco-ise-get-endpoint-id'
      type: regular
      version: -1
    taskid: c24d2176-d3d3-4c0c-8a83-e63359322dd3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 490
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 7d88fc34-8b78-4562-8377-27461ecc8257
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 7d88fc34-8b78-4562-8377-27461ecc8257
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 670
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Endpoint ${incident.macAddress} does not exist on ISE.
      playbook-name:
        simple: panw_iot_ise_unquarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: d9bfc125-620d-43bb-82b5-8ed5d810be00
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: d9bfc125-620d-43bb-82b5-8ed5d810be00
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": 840
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      attributeName:
        simple: ZingboxAlertType,ZingboxAlertSeverity
      attributeValue:
        simple: ','
      id:
        simple: ${Endpoint.ID}
      macAddress:
        simple: ${Endpoint.MACAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Updates the custom attributes of an endpoint.
      id: adf7dd93-be05-4fbf-8876-78e5be176000
      iscommand: true
      name: cisco-ise-update-endpoint-custom-attribute
      script: '|||cisco-ise-update-endpoint-custom-attribute'
      type: regular
      version: -1
    taskid: adf7dd93-be05-4fbf-8876-78e5be176000
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 960
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 16f10fc0-a85e-4e2a-88f0-5d6d2287c56d
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 16f10fc0-a85e-4e2a-88f0-5d6d2287c56d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 520,
          "y": 1200
        }
      }
  "10":
    continueonerror: true
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Failed to un-quarantine Endpoint ${Endpoint.MACAddress} on ISE
      playbook-name:
        simple: panw_iot_ise_unquarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 656968b8-7e05-4af8-8599-d82f1dacd1cb
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 656968b8-7e05-4af8-8599-d82f1dacd1cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 770,
          "y": 1400
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Un-Quarantine Successful for Endpoint ${Endpoint.MACAddress}
      playbook-name:
        simple: panw_iot_ise_unquarantine_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: ce8e7c69-ed9c-4140-80ac-c3b8d13525b2
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: ce8e7c69-ed9c-4140-80ac-c3b8d13525b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": 1400
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: c9b50755-2f0b-42dc-8ba3-8c5fe93835ca
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c9b50755-2f0b-42dc-8ba3-8c5fe93835ca
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1700
        }
      }
  "13":
    continueonerror: true
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This Scripts pulls all ISE deployment node details and check if
        there is any node thats either a standalone OR a primary node and the node
        matches the instance configured by the user.
      id: 7fb9d82c-0510-48f4-8613-50cf362b4471
      iscommand: false
      name: panw_iot_get_active_ise_instance
      script: f25e9856-47b3-49c6-8d5b-abf33811e17f
      type: regular
      version: -1
    taskid: 7fb9d82c-0510-48f4-8613-50cf362b4471
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": -130
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: fb5c75f1-29cd-4d8d-8777-7a7a835d8ea2
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: fb5c75f1-29cd-4d8d-8777-7a7a835d8ea2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 420,
          "y": 110
        }
      }
  "15":
    continueonerror: true
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: ${PaloAltoIoTIntegrationBase.NodeErrorStatus}
      playbook-name:
        simple: panw_iot_ise_unquarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: e8a379ea-b279-4840-881f-7eaebe85db4d
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: e8a379ea-b279-4840-881f-7eaebe85db4d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": 300
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "9_11_no": 0.72
    },
    "paper": {
      "dimensions": {
        "height": 2295,
        "width": 1360,
        "x": -210,
        "y": -500
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
