description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to quarantine
  a device in ISE
id: panw_iot_ise_quarantine_playbook
inputs: []
name: panw_iot_ise_quarantine_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_ise_quarantine"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f5f97dff-b6c8-442e-89b9-b31fbe70cbb9
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: f5f97dff-b6c8-442e-89b9-b31fbe70cbb9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE Copy
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 72e325de-f67e-460a-84d2-8eb181de6772
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 72e325de-f67e-460a-84d2-8eb181de6772
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Cisco Ise instance not configured
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 8718bd77-1069-4606-8bb5-6e2968f500eb
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 8718bd77-1069-4606-8bb5-6e2968f500eb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -30,
          "y": 460
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      macAddress:
        simple: ${incident.macAddress}
      using:
        simple: PANW IoT ise Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco ISE Copy
      description: Returns an endpoint ID, by its MAC address.
      id: 55a4620f-bbfb-417f-8426-91aa758ccbef
      iscommand: true
      name: cisco-ise-get-endpoint-id
      script: Cisco ISE Copy|||cisco-ise-get-endpoint-id
      type: regular
      version: -1
    taskid: 55a4620f-bbfb-417f-8426-91aa758ccbef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 490
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: d5945d4a-3ca7-49e0-81fb-2f7f2a5f8ce9
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: d5945d4a-3ca7-49e0-81fb-2f7f2a5f8ce9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 670
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Endpoint ${incident.macAddress} does not exist on ISE.
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: b07a9982-902f-4e0b-88dc-a3b997bb3a61
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: b07a9982-902f-4e0b-88dc-a3b997bb3a61
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": 840
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      attributeName:
        simple: ZingboxAlertType,ZingboxAlertSeverity
      attributeValue:
        simple: ${incident.alertType},${incident.alertSeverity}
      id:
        simple: ${Endpoint.ID}
      macAddress:
        simple: ${Endpoint.MACAddress}
      using:
        simple: PANW IoT ise Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cisco ISE Copy
      description: Updates the custom attributes of an endpoint.
      id: b388ba8f-9e81-42b1-8f47-54f343a740bb
      iscommand: true
      name: cisco-ise-update-endpoint-custom-attribute
      script: Cisco ISE Copy|||cisco-ise-update-endpoint-custom-attribute
      type: regular
      version: -1
    taskid: b388ba8f-9e81-42b1-8f47-54f343a740bb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 960
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 8d078f45-6533-4fc1-8d53-de3db5e65f5a
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 8d078f45-6533-4fc1-8d53-de3db5e65f5a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 520,
          "y": 1200
        }
      }
  "10":
    continueonerror: true
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Failed to Quarantine Endpoint ${Endpoint.MACAddress} on ISE
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: d8c96728-cf36-4c14-8991-39dc10af51cc
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: d8c96728-cf36-4c14-8991-39dc10af51cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 770,
          "y": 1400
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Quarantine Successful for Endpoint ${Endpoint.MACAddress}
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 0580af82-79fe-45ed-8266-2a907ae2569f
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 0580af82-79fe-45ed-8266-2a907ae2569f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": 1400
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: e1148ee3-b303-4780-8118-70d399153ad2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e1148ee3-b303-4780-8118-70d399153ad2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1700
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "9_11_no": 0.72
    },
    "paper": {
      "dimensions": {
        "height": 1745,
        "width": 1360,
        "x": -210,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)