description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to quarantine
  a device in ISE
id: panw_iot_ise_quarantine_playbook
inputs: []
name: panw_iot_ise_quarantine_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_ise_quarantine"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2cc2a937-0b94-4b65-8474-2db60f28f198
      iscommand: false
      name: ""
      version: -1
    taskid: 2cc2a937-0b94-4b65-8474-2db60f28f198
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 390,
          "y": -410
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE Copy
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 57dec759-c333-4526-8a5b-bc7bd59d4970
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 57dec759-c333-4526-8a5b-bc7bd59d4970
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 400,
          "y": -280
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Cisco ISE instance is not enabled
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: disabled
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 4b697d9d-2cb8-4f75-88fc-a0f91207e1ad
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 4b697d9d-2cb8-4f75-88fc-a0f91207e1ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -60,
          "y": 230
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      macAddress:
        simple: ${incident.macAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns an endpoint ID, by its MAC address.
      id: 8604019f-76ba-4a6f-83d5-cea3a07d8ff4
      iscommand: true
      name: cisco-ise-get-endpoint-id
      script: '|||cisco-ise-get-endpoint-id'
      type: regular
      version: -1
    taskid: 8604019f-76ba-4a6f-83d5-cea3a07d8ff4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 500
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      "no":
      - "8"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 2642cac5-dea3-49ea-8c04-8eacc4d74e95
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 2642cac5-dea3-49ea-8c04-8eacc4d74e95
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 530,
          "y": 680
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Endpoint ${incident.macAddress} does not exist on ISE.
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 5c4d18cb-05e7-4f0c-8ec0-aa11e97344fa
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 5c4d18cb-05e7-4f0c-8ec0-aa11e97344fa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 70,
          "y": 890
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      attributeName:
        simple: ZingboxAlertType,ZingboxAlertSeverity
      attributeValue:
        simple: ${incident.alertType},${incident.alertSeverity}
      id:
        simple: ${Endpoint.ID}
      macAddress:
        simple: ${Endpoint.MACAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Updates the custom attributes of an endpoint.
      id: 7917d977-179a-4029-8aca-4b8f9ce102d7
      iscommand: true
      name: cisco-ise-update-endpoint-custom-attribute
      script: '|||cisco-ise-update-endpoint-custom-attribute'
      type: regular
      version: -1
    taskid: 7917d977-179a-4029-8aca-4b8f9ce102d7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 960
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 9727e8eb-fd75-4665-8876-65ac226cd785
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 9727e8eb-fd75-4665-8876-65ac226cd785
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 520,
          "y": 1200
        }
      }
  "10":
    continueonerror: true
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Failed to Quarantine Endpoint ${Endpoint.MACAddress} on ISE
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 2987e4d6-f800-4a0e-88e1-556c58a263b9
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 2987e4d6-f800-4a0e-88e1-556c58a263b9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 770,
          "y": 1400
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Quarantine Successful for Endpoint ${Endpoint.MACAddress}
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 10f7bd5b-9fc0-4290-8f74-1cc54586fe1e
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 10f7bd5b-9fc0-4290-8f74-1cc54586fe1e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": 1400
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: fa7bec23-6065-4779-8655-2f4ef1e45b2c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: fa7bec23-6065-4779-8655-2f4ef1e45b2c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1700
        }
      }
  "13":
    continueonerror: true
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This Scripts pulls all ISE deployment node details and check if
        there is any node thats either a standalone OR a primary node and the node
        matches the instance configured by the user.
      id: 1f31e724-dca5-47b4-8e52-5a3ba4c0c684
      iscommand: false
      name: panw_iot_get_active_ise_instance
      script: f25e9856-47b3-49c6-8d5b-abf33811e17f
      type: regular
      version: -1
    taskid: 1f31e724-dca5-47b4-8e52-5a3ba4c0c684
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 550,
          "y": 20
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: b766e9a8-7a05-4811-8b58-463e43f20628
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: b766e9a8-7a05-4811-8b58-463e43f20628
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 560,
          "y": 220
        }
      }
  "15":
    continueonerror: true
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: ${PaloAltoIoTIntegrationBase.NodeErrorStatus}
      playbook-name:
        simple: panw_iot_ise_quarantine_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 4c9e2e66-2db4-4b69-8259-29341e6a1cfe
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 4c9e2e66-2db4-4b69-8259-29341e6a1cfe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 200,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "9_11_no": 0.72
    },
    "paper": {
      "dimensions": {
        "height": 2205,
        "width": 1360,
        "x": -210,
        "y": -410
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
