description: This playbook gets all available assets ( alerts, vulnerabilities and
  devices) and send then to configured PANW third-party integration SIEM server
id: panw_iot_siem_bulk_integration
inputs: []
name: panw_iot_siem_bulk_integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 615e6420-5316-4b4a-8674-9a65ba14b131
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 615e6420-5316-4b4a-8674-9a65ba14b131
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 520,
          "y": -180
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance,PANW IoT Siem
          Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: gets all available devices from the IoT cloud and sends it to the
        SIEM server
      id: d576d007-05d5-4150-8f5a-d61989421f4d
      iscommand: false
      name: send_bulk_panw_iot_devices_to_siem
      script: send_bulk_panw_iot_devices_to_siem
      type: regular
      version: -1
    taskid: d576d007-05d5-4150-8f5a-d61989421f4d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": 440
        }
      }
  "2":
    continueonerror: true
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance,PANW IoT Siem
          Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: gets all available alerts from the IoT cloud and sends it to the
        SIEM server
      id: bdf60ed5-3a76-4f32-88e3-2aca08c76c9c
      iscommand: false
      name: send_bulk_panw_iot_alerts_to_siem
      script: send_bulk_panw_iot_alerts_to_siem
      type: regular
      version: -1
    taskid: bdf60ed5-3a76-4f32-88e3-2aca08c76c9c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 440
        }
      }
  "3":
    continueonerror: true
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: PANW IoT Siem Instance,Palo Alto IoT Third-Party-Integration Base
          Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: gets all available vulnerabilities from the IoT cloud and sends
        it to the SIEM server
      id: b855239c-1133-4864-8951-211cfa79fa00
      iscommand: false
      name: send_bulk_panw_iot_vulnerabilities_to_siem
      script: send_bulk_panw_iot_vulnerabilities_to_siem
      type: regular
      version: -1
    taskid: b855239c-1133-4864-8951-211cfa79fa00
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 430
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "3"
      - "2"
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: efd6a802-b709-4f77-8fed-9a08a33c253f
      iscommand: false
      name: IsIntegrationAvailable
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: efd6a802-b709-4f77-8fed-9a08a33c253f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 520,
          "y": 30
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: Syslog Sender (SIEM) instance is not enabled
      playbook-name:
        simple: panw_iot_siem_bulk_integration
      status:
        simple: disabled
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 90bb3ea7-6294-4063-84ae-00ccb4ac2a3a
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 90bb3ea7-6294-4063-84ae-00ccb4ac2a3a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1240,
          "y": 230
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 7b2b626b-1b6a-4277-8880-304c8ae57d25
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 7b2b626b-1b6a-4277-8880-304c8ae57d25
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 970
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1245,
        "width": 1530,
        "x": 90,
        "y": -180
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
