description: |
  This playbook gets all available device inventory and updates/create endpoints with custom attributes on Cisco ISE
id: panw_iot_ise_bulk_integration
inputs: []
name: panw_iot_ise_bulk_integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4eb678ce-b363-4819-8487-73b2295a3c25
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 4eb678ce-b363-4819-8487-73b2295a3c25
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE Copy
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: f8213eba-04d9-47da-88cb-a79c1ea1f584
      iscommand: false
      name: IsIntegrationAvailable
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: f8213eba-04d9-47da-88cb-a79c1ea1f584
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerror: true
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Cisco Ise instance not configured
      playbook-name:
        simple: panw_iot_ise_bulk_integration
      status:
        simple: error
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 3422cb56-4d63-4a57-873c-e207534c58a9
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 3422cb56-4d63-4a57-873c-e207534c58a9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 410
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance,PANW IoT ise Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This script gets all available devices from the IoT cloud and updates/creates
        new endpoint with custom attributes on Cisco ISE
      id: 2e598456-205e-4232-88e8-a3b84c78fa9a
      iscommand: false
      name: send_bulk_panw_iot_devices_to_ise
      script: send_bulk_panw_iot_devices_to_ise
      type: regular
      version: -1
    taskid: 2e598456-205e-4232-88e8-a3b84c78fa9a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 540
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 7a5a4c57-f093-473e-8148-80bf405c12e1
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 7a5a4c57-f093-473e-8148-80bf405c12e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 430,
          "y": 810
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 855,
        "width": 840,
        "x": 60,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
