description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Alert to SIEM
id: panw_iot_siem_single_alert_playbook
inputs: []
name: panw_iot_siem_single_alert_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_siem_alert"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9d239df0-34f0-47c5-8011-755357303ac3
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 9d239df0-34f0-47c5-8011-755357303ac3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: ba606cca-e627-4f2f-8bc3-dfa71c533bf3
      iscommand: false
      name: Is  SIEM enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ba606cca-e627-4f2f-8bc3-dfa71c533bf3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: SIEM Integration not enabled
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: e5c0c980-41c4-49c3-84f4-df242147046b
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: e5c0c980-41c4-49c3-84f4-df242147046b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${incident.zb_ticketid}
      asset_type:
        simple: Alerts
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: Given a id (alert-id, vulnerability-id or mac-address) returns
        the asset details
      id: 9ee4aff1-9248-473c-8d9e-b4fe64978324
      iscommand: true
      name: get-single-alert-details
      script: Palo Alto IoT Third-Party-Integration Base|||get-single-asset-details
      type: regular
      version: -1
    taskid: 9ee4aff1-9248-473c-8d9e-b4fe64978324
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "6":
    continueonerror: true
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      alertList:
        simple: ${PaloAltoIoTIntegrationBase.SingleAsset}
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: Converts alert detail maps to CEF syslogs
      id: 05ae397e-11de-40ca-8567-7756392bce3a
      iscommand: true
      name: convert-alerts-to-cef
      script: Palo Alto IoT Third-Party-Integration Base|||convert-alerts-to-cef
      type: regular
      version: -1
    taskid: 05ae397e-11de-40ca-8567-7756392bce3a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      address: {}
      facility: {}
      level: {}
      message:
        simple: ${PaloAltoIoTIntegrationBase.AlertSyslogs}
      port: {}
      protocol: {}
      using:
        simple: PANW IoT Siem Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Syslog Sender
      description: Sends a message to Syslog.
      id: 208bfa3c-6851-447f-88f6-10639e2c6d42
      iscommand: true
      name: syslog-send
      script: Syslog Sender|||syslog-send
      type: regular
      version: -1
    taskid: 208bfa3c-6851-447f-88f6-10639e2c6d42
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1230
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 306373fd-9093-4e88-8a1b-f0e323eb9aba
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 306373fd-9093-4e88-8a1b-f0e323eb9aba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: Failed to get Alert (${incident.zb_ticketid}) from IoT cloud.
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: fdbcd4ca-f4ff-4773-8075-7bcc652e8e3a
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: fdbcd4ca-f4ff-4773-8075-7bcc652e8e3a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PaloAltoIoTIntegrationBase.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 92f06baf-0e1f-4d84-8055-e6b982a615be
      iscommand: false
      name: Exists
      script: Exists
      type: condition
      version: -1
    taskid: 92f06baf-0e1f-4d84-8055-e6b982a615be
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: No Alert found with given ID  (${incident.zb_ticketid}).
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 0afd4e82-1cbf-46db-84e0-7a1037bf7fae
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 0afd4e82-1cbf-46db-84e0-7a1037bf7fae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 910
        }
      }
  "12":
    continueonerror: true
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: Successfully sent Alert (${incident.zb_ticketid}) to SIEM
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 07bf1354-6b3d-4b20-8526-c6f416a1936f
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 07bf1354-6b3d-4b20-8526-c6f416a1936f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1430
        }
      }
  "13":
    continueonerror: true
    id: "13"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 3fa50458-fad8-49a5-8a30-ca2003964115
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 3fa50458-fad8-49a5-8a30-ca2003964115
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1675
        }
      }
  "14":
    continueonerror: true
    id: "14"
    ignoreworker: false
    nexttasks:
      "no":
      - "15"
      "yes":
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PaloAltoIoTIntegrationBase.AlertSyslogs}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 7b4c93f9-534c-48e5-819d-d2a44b345ad1
      iscommand: false
      name: Exists
      script: Exists
      type: condition
      version: -1
    taskid: 7b4c93f9-534c-48e5-819d-d2a44b345ad1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1040
        }
      }
  "15":
    continueonerror: true
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: No Alert found with given ID  (${incident.zb_ticketid}).
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 94551eda-7d46-45c0-8d6e-160835162e06
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 94551eda-7d46-45c0-8d6e-160835162e06
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1075,
          "y": 1120
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1720,
        "width": 1405,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
