description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  unquarantine a device in ISE
id: 09990d44-43e8-42a2-8521-d9fff17ad2cb
inputs: []
name: panw_iot_ise_unquarantine_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_ise_unquarantine"
  type: unknown
sourceplaybookid: 4bdb8bfb-119b-44bb-8eb2-eeb81c447c49
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ff1b9a9c-2efb-4c76-82b6-e31279d89e1b
      iscommand: false
      name: ""
      version: -1
    taskid: ff1b9a9c-2efb-4c76-82b6-e31279d89e1b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 1a47a285-3fda-411d-820e-7dd9728f81e0
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 1a47a285-3fda-411d-820e-7dd9728f81e0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: alert
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: b8bc0a58-9510-4e3f-83dc-43bf0cd6bbc9
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: b8bc0a58-9510-4e3f-83dc-43bf0cd6bbc9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Integration not Configured
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 7eba1d22-62c6-40a5-8538-3dc5cb892388
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 7eba1d22-62c6-40a5-8538-3dc5cb892388
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 450
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 495,
        "width": 790,
        "x": 40,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
