description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to quarantine
  a device in ISE
id: panw_iot_ise_quarantine_playbook
inputs: []
name: panw_iot_ise_quarantine_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_ise_quarantine"
  type: unknown
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b5d44bf8-0221-4935-8127-2079444b9720
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: b5d44bf8-0221-4935-8127-2079444b9720
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 521106a5-0a5d-429e-8d67-27662958f49a
      iscommand: false
      name: Is Cisco ISE enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 521106a5-0a5d-429e-8d67-27662958f49a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: alert
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a659b8d1-c4ed-433e-8667-bd96043096d5
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: a659b8d1-c4ed-433e-8667-bd96043096d5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Integration not Configured
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 3d89a5c7-2973-4f7d-877f-b3bd7a6cc2f4
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 3d89a5c7-2973-4f7d-877f-b3bd7a6cc2f4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 450
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 495,
        "width": 790,
        "x": 40,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
