description: This playbook gets all available device inventory from PANW IoT cloud
  send to ServiceNow
id: panw_iot_servicenow_device_bulk_sync_playbook
inputs: []
name: panw_iot_servicenow_device_bulk_sync_playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a42eb1b0-e0f2-4a77-8828-ae1f8f4ec099
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: a42eb1b0-e0f2-4a77-8828-ae1f8f4ec099
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This script gets all available devices from the IoT cloud and updates/creates
        new endpoint with custom attributes on ServiceNow
      id: 6d44f8d0-5aca-47fb-84d3-bf67c95083f3
      iscommand: false
      name: send_bulk_panw_iot_devices_to_servicenow
      script: send_bulk_panw_iot_devices_to_servicenow
      type: regular
      version: -1
    taskid: 6d44f8d0-5aca-47fb-84d3-bf67c95083f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: f1d49ef6-5ce3-4ad1-8090-d8debb6cbd1e
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f1d49ef6-5ce3-4ad1-8090-d8debb6cbd1e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: bff7bbb9-15cc-443a-8f5b-1ccf8b00f964
      iscommand: false
      name: Is servicenow available
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: bff7bbb9-15cc-443a-8f5b-1ccf8b00f964
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: servicenow
      message:
        simple: ServiceNow instance is not enabled
      playbook-name:
        simple: panw_iot_servicenow_device_bulk_sync_playbook
      status:
        simple: disabled
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 99081c0f-9ca7-426f-8f4e-df6bf3ae7cbf
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 99081c0f-9ca7-426f-8f4e-df6bf3ae7cbf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 320
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: be48c9c3-e6cd-4e19-81e7-37192cebc565
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: be48c9c3-e6cd-4e19-81e7-37192cebc565
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 850,
          "y": 555
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 755,
        "width": 780,
        "x": 450,
        "y": 50
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
