description: This playbook gets all available assets ( alerts, vulnerabilities and
  devices) and send then to configured PANW third-party integration SIEM server
id: panw_iot_siem_bulk_integration
inputs: []
name: panw_iot_siem_bulk_integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 710b2102-94bd-438f-8485-c6f246a513ab
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 710b2102-94bd-438f-8485-c6f246a513ab
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 520,
          "y": -180
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance,PANW IoT Siem
          Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: gets all available devices from the IoT cloud and sends it to the
        SIEM server
      id: f2909d40-74f9-4528-8941-9f035dd9408e
      iscommand: false
      name: send_bulk_panw_iot_devices_to_siem
      script: send_bulk_panw_iot_devices_to_siem
      type: regular
      version: -1
    taskid: f2909d40-74f9-4528-8941-9f035dd9408e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": 440
        }
      }
  "2":
    continueonerror: true
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance,PANW IoT Siem
          Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: gets all available alerts from the IoT cloud and sends it to the
        SIEM server
      id: 31c824cc-8d45-4a6d-8b6f-02b5c5bb17a1
      iscommand: false
      name: send_bulk_panw_iot_alerts_to_siem
      script: send_bulk_panw_iot_alerts_to_siem
      type: regular
      version: -1
    taskid: 31c824cc-8d45-4a6d-8b6f-02b5c5bb17a1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 440
        }
      }
  "3":
    continueonerror: true
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: PANW IoT Siem Instance,Palo Alto IoT Third-Party-Integration Base
          Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: gets all available vulnerabilities from the IoT cloud and sends
        it to the SIEM server
      id: 18e7ce4b-abf6-4dd0-8b5c-822ea9d233e6
      iscommand: false
      name: send_bulk_panw_iot_vulnerabilities_to_siem
      script: send_bulk_panw_iot_vulnerabilities_to_siem
      type: regular
      version: -1
    taskid: 18e7ce4b-abf6-4dd0-8b5c-822ea9d233e6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 430
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "3"
      - "2"
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 6209ec04-fdf1-4293-89e4-251bf6b4f210
      iscommand: false
      name: IsIntegrationAvailable
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 6209ec04-fdf1-4293-89e4-251bf6b4f210
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 520,
          "y": 30
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: syslog server (SIEM) not configured
      playbook-name:
        simple: panw_iot_siem_bulk_integration
      status:
        simple: error
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: ee34dffa-6f9d-410b-8b9c-90d664dcfd12
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: ee34dffa-6f9d-410b-8b9c-90d664dcfd12
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1240,
          "y": 230
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 1b3b66c5-219c-444f-8d90-e43cb24f76ec
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1b3b66c5-219c-444f-8d90-e43cb24f76ec
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 530,
          "y": 970
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1245,
        "width": 1530,
        "x": 90,
        "y": -180
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
