description: |
  Playbook to be run every 15 minutes via a job. Each run will get incremental updates for devices, and will update or create new endpoints in ise with PANW IOT discovered attributes (ise custom attributes)
id: panw_iot_ise_integration
inputs: []
name: panw_iot_ise_integration
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b02a887-d90f-4311-818a-280703e54fdf
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 8b02a887-d90f-4311-818a-280703e54fdf
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 240,
          "y": 0
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: Gets a list of devices detected/modified within the last 15 minutes
      id: 35f04f83-a2ce-4e26-8123-339fe5b5ab38
      iscommand: true
      name: get-incremental-device-inventory
      script: Palo Alto IoT Third-Party-Integration Base|||get-incremental-device-inventory
      type: regular
      version: -1
    taskid: 35f04f83-a2ce-4e26-8123-339fe5b5ab38
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 570,
          "y": 425
        }
      }
  "2":
    continueonerror: true
    id: "2"
    ignoreworker: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Cisco ISE Copy
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 7f6823ab-e1e0-492b-812a-95f597f45511
      iscommand: false
      name: IsIntegrationAvailable
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 7f6823ab-e1e0-492b-812a-95f597f45511
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 240,
          "y": 200
        }
      }
  "3":
    continueonerror: true
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Cisco ISE instance is not configured
      playbook-name:
        simple: ise
      status:
        simple: error
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 039fea96-4c84-4220-8577-0677dbc681ad
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 039fea96-4c84-4220-8577-0677dbc681ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -370,
          "y": 425
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      device_maps:
        simple: ${PaloAltoIoTIntegrationBase.Devices.asset_list}
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: converts PANW Iot device attribute map to ISE custom attributees
      id: c2270f31-6a6a-4004-82d1-d1a4e8a9a0aa
      iscommand: true
      name: convert-device-inventory-to-ise-custom-attributes
      script: Palo Alto IoT Third-Party-Integration Base|||convert-device-inventory-to-ise-custom-attributes
      type: regular
      version: -1
    taskid: c2270f31-6a6a-4004-82d1-d1a4e8a9a0aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 900
        }
      }
  "6":
    continueonerror: true
    id: "6"
    ignoreworker: false
    nexttasks:
      "no":
      - "15"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 756ca155-5dad-4e8b-8cf9-f85ba7c39b5f
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 756ca155-5dad-4e8b-8cf9-f85ba7c39b5f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1830
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      device_maps:
        simple: ${PaloAltoIoTIntegrationBase.CisceISEAttributes}
      using:
        simple: PANW IoT ise Instance,Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'For a give device map (from PANW IoT cloud) check if the device
        exists in Cisco ISE. If the output exists, the script will return the mac
        address other wise return nothing. '
      id: a61fb04d-bb08-4281-89f4-712b16b26699
      iscommand: false
      name: send_panw_iot_devices_to_ise
      script: send_panw_iot_devices_to_ise
      type: regular
      version: -1
    taskid: a61fb04d-bb08-4281-89f4-712b16b26699
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 1570
        }
      }
  "10":
    continueonerror: true
    id: "10"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: ceca7161-427f-43a7-84d3-1501166cec80
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: ceca7161-427f-43a7-84d3-1501166cec80
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 570,
          "y": 690
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Failed to get device inventory from PANW IoT Cloud
      playbook-name:
        simple: ise
      status:
        simple: error
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 1ab5e414-705d-48f3-8dfa-faf14be95a0c
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 1ab5e414-705d-48f3-8dfa-faf14be95a0c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 180,
          "y": 920
        }
      }
  "12":
    continueonerror: true
    id: "12"
    ignoreworker: false
    nexttasks:
      "no":
      - "17"
      "yes":
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 1f8103e2-ce2f-4875-85fa-c58cd62de6f4
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 1f8103e2-ce2f-4875-85fa-c58cd62de6f4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 780,
          "y": 1125
        }
      }
  "13":
    continueonerror: true
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Failed to convert device inventory to Cisco ISE custom attributes
      playbook-name:
        simple: ise
      status:
        simple: error
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 267b2602-955c-44dd-8361-71fbc1e0ab9f
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 267b2602-955c-44dd-8361-71fbc1e0ab9f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": 1360
        }
      }
  "14":
    continueonerror: true
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: Update custom attributes script failed
      playbook-name:
        simple: ise
      status:
        simple: error
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 78a47560-97eb-4141-848c-82894378e2ef
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 78a47560-97eb-4141-848c-82894378e2ef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": 2020
        }
      }
  "15":
    continueonerror: true
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: ${PaloAltoIoTIntegrationBase.Status}
      playbook-name:
        simple: ise
      status:
        simple: success
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 8f61e004-5035-4449-8813-cfc8a5dbf928
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 8f61e004-5035-4449-8813-cfc8a5dbf928
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 2125
        }
      }
  "16":
    continueonerror: true
    id: "16"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 26eccc40-df87-4df5-80eb-a31654d52ca7
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 26eccc40-df87-4df5-80eb-a31654d52ca7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 270,
          "y": 2440
        }
      }
  "17":
    continueonerror: true
    id: "17"
    ignoreworker: false
    nexttasks:
      "no":
      - "18"
      "yes":
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PaloAltoIoTIntegrationBase.CisceISEAttributes}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 310caaba-799b-42a3-860b-1a216fc042c1
      iscommand: false
      name: Exists
      script: Exists
      type: condition
      version: -1
    taskid: 310caaba-799b-42a3-860b-1a216fc042c1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1100,
          "y": 1350
        }
      }
  "18":
    continueonerror: true
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: ise
      message:
        simple: No new devices available for updating in ISE
      playbook-name:
        simple: ise
      status:
        simple: success
      type:
        simple: device
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 5f7131f8-7da8-4205-856a-059f035a4427
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 5f7131f8-7da8-4205-856a-059f035a4427
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": 1700
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2535,
        "width": 1860,
        "x": -370,
        "y": 0
      }
    }
  }
fromversion: 5.5.0
tests:
- No tests (auto formatted)
