description: Playbook to handle incident triggered from PANW Iot (Zingbox) UI to send
  Alert to SIEM
id: 9ac344da-b5c6-4c3d-879e-21faeb9660e2
inputs: []
name: panw_iot_siem_single_alert_playbook
outputs:
- contextPath: incident
  description: This playbook is invoked via the incident type "panw_iot_siem_alert"
  type: unknown
sourceplaybookid: 4bdb8bfb-119b-44bb-8eb2-eeb81c447c49
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ff1b9a9c-2efb-4c76-82b6-e31279d89e1b
      iscommand: false
      name: ""
      version: -1
    taskid: ff1b9a9c-2efb-4c76-82b6-e31279d89e1b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Syslog Sender
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: ea86a7bf-f167-46a7-89a7-83f15fa21a3b
      iscommand: false
      name: Is  SIEM enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ea86a7bf-f167-46a7-89a7-83f15fa21a3b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "4":
    continueonerror: true
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: SIEM Integration not enabled
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: fbe8886c-8e9e-4a32-8c65-cc2000e6401b
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: fbe8886c-8e9e-4a32-8c65-cc2000e6401b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      asset_id:
        simple: ${incident.zb_ticketid}
      asset_type:
        simple: Alerts
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: Given a id (alert-id, vulnerability-id or mac-address) returns
        the asset details
      id: 7d5e0ac3-461f-49e4-8152-9b9206fb00b2
      iscommand: true
      name: get-single-alert-details
      script: Palo Alto IoT Third-Party-Integration Base|||get-single-asset-details
      type: regular
      version: -1
    taskid: 7d5e0ac3-461f-49e4-8152-9b9206fb00b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "6":
    continueonerror: true
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      alertList:
        simple: ${PaloAltoIoTIntegrationBase.SingleAsset}
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: Converts alert detail maps to CEF syslogs
      id: 6a0a02d2-e4dd-40e5-8dfd-3789aa2f5e35
      iscommand: true
      name: convert-alerts-to-cef
      script: Palo Alto IoT Third-Party-Integration Base|||convert-alerts-to-cef
      type: regular
      version: -1
    taskid: 6a0a02d2-e4dd-40e5-8dfd-3789aa2f5e35
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "7":
    continueonerror: true
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      address: {}
      facility: {}
      level: {}
      message:
        simple: ${PaloAltoIoTIntegrationBase.AlertSyslogs}
      port: {}
      protocol: {}
      using:
        simple: PANW IoT Siem Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Syslog Sender
      description: Sends a message to Syslog.
      id: 3cc0ce42-64fd-448f-8fe0-90978b6827da
      iscommand: true
      name: syslog-send
      script: Syslog Sender|||syslog-send
      type: regular
      version: -1
    taskid: 3cc0ce42-64fd-448f-8fe0-90978b6827da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "8":
    continueonerror: true
    id: "8"
    ignoreworker: false
    nexttasks:
      "no":
      - "10"
      "yes":
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 4d440d99-321d-41df-8e86-fdd2dbe840bf
      iscommand: false
      name: isError
      script: isError
      type: condition
      version: -1
    taskid: 4d440d99-321d-41df-8e86-fdd2dbe840bf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "9":
    continueonerror: true
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: Failed to get Alert (${incident.zb_ticketid}) from IoT cloud.
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: error
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 979010a0-db52-4b3a-88ec-20417b880f65
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 979010a0-db52-4b3a-88ec-20417b880f65
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      "no":
      - "11"
      "yes":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${PaloAltoIoTIntegrationBase.SingleAsset}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 404aa72a-f4ad-42d2-8290-af30532f7563
      iscommand: false
      name: Exists
      script: Exists
      type: condition
      version: -1
    taskid: 404aa72a-f4ad-42d2-8290-af30532f7563
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "11":
    continueonerror: true
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: No Alert found with given ID  (${incident.zb_ticketid}).
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: 83a92550-4887-4233-8675-f6d27202326a
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: 83a92550-4887-4233-8675-f6d27202326a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 910
        }
      }
  "12":
    continueonerror: true
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      integration-name:
        simple: siem
      message:
        simple: Successfully sent Alert (${incident.zb_ticketid}) to SIEM
      playbook-name:
        simple: panw_iot_siem_single_alert_playbook
      status:
        simple: success
      type:
        simple: alert
      using:
        simple: Palo Alto IoT Third-Party-Integration Base Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      description: sends a status message back to PANW IOT cloud
      id: d625355e-319c-4802-8ec4-400d30c38e58
      iscommand: true
      name: send-status-to-panw-iot-cloud
      script: Palo Alto IoT Third-Party-Integration Base|||send-status-to-panw-iot-cloud
      type: regular
      version: -1
    taskid: d625355e-319c-4802-8ec4-400d30c38e58
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1295
        }
      }
  "13":
    continueonerror: true
    id: "13"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 87dbe8e7-cd31-4dae-853e-c1a412224542
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 87dbe8e7-cd31-4dae-853e-c1a412224542
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1475
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1520,
        "width": 1360,
        "x": 50,
        "y": 50
      }
    }
  }
