id: 4631ee40-e1b1-4d77-856c-601214453913
inputs: []
name: test save file to local
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f64ad155-794e-4630-8936-00a4c1639ae0
      iscommand: false
      name: ""
      version: -1
    taskid: f64ad155-794e-4630-8936-00a4c1639ae0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Palo Alto IoT Third-Party-Integration Base
      id: bb0f305c-b151-4e55-8fdb-5f2c25e25420
      iscommand: true
      name: save-to-local-files
      script: Palo Alto IoT Third-Party-Integration Base|||save-to-local-files
      type: regular
      version: -1
    taskid: bb0f305c-b151-4e55-8fdb-5f2c25e25420
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: e95a3cb7-588a-47f0-8ecc-25967cbb85f2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e95a3cb7-588a-47f0-8ecc-25967cbb85f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
